# Generated by Django 4.2.9 on 2024-03-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_request_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('source', models.URLField(db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
